# Cloudflare Workers 配置
name = "games-platform"
main = "workers-site/index.js"
compatibility_date = "2023-09-01"

# 静态网站配置
[site]
bucket = "./dist"

# 构建配置
[build]
command = "npm run build"

# KV命名空间配置
[[kv_namespaces]]
binding = "ASSETS"
id = "8f6bffafce894d109d4d930e39e7f474"
