# Cloudflare Pages 配置
name = "games-platform"
compatibility_date = "2023-09-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"

# 配置SPA路由
[site.mounts]
source = "./dist"
destination = "/"

# SPA后备配置
[site.static_error_page]
default = "/index.html"
