# Cloudflare Workers 配置
name = "games-platform"
main = "workers-site/index.js"
compatibility_date = "2023-09-01"

# 静态网站配置
[site]
bucket = "./dist"

# 构建配置
[build]
command = "npm run build"

# KV命名空间配置
[[kv_namespaces]]
binding = "ASSETS"
id = ""  # 警告: 部署前必须运行 'npm run predeploy' 或 'node scripts/setup-kv.js' 来填充此ID
