# Cloudflare Workers 配置
name = "games-platform"
main = "workers-site/index.js"
compatibility_date = "2023-09-01"

# 静态网站配置
[site]
bucket = "./dist"

# 构建配置
[build]
command = "npm run build"

# 配置SPA路由
[site.mounts]
source = "./dist"
destination = "/"

# SPA后备配置
[site.static_error_page]
default = "/index.html"
